service: <%= kebabCasedName %>

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    packager: yarn

provider:
  name: aws
  region: <%= region %>
  runtime: nodejs14.x

functions:
  myFunction:
    handler: src/myFunction.handler
