service: <%= kebabCasedName %>

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  region: <%= region %>
  runtime: nodejs14.x

functions:
  myFunction:
    handler: src/myFunction.handler
